# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb10bff91e24b6fcb868ebe30dcad6d0f9b03d1043f247b7b3c12894650499b967ad24cf55b33537e236dc7b317cd5244dadc577ea78450d0a7463fac2aab6e8

test:
  secret_key_base: fa85376022a727899cd090ab084e7abf97b5f09f09e4d84db1f36db26916d7fa0b655a3cdd4c672f413f434c95dac9dd82e2427a21188d34308f4a397c2e320a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
